### ISSUE TITLE
Pick up dependencies from pyproject.toml?

### ISSUE THREAD

**Issue by connortann** [conda-forge/shap-feedstock#58]
Proposal for a future enhancement:

SHAP now specifies its build and run dependencies in pyproject.toml, according to PEP 518. We could potentially pick up dependencies from there, rather than maintaining a separate list of build dependencies in this repo.

It looks like this would require `load_file_data` , which will be available in the next release of conda-build (probably out in a month or two).
https://github.com/conda/conda-build/pull/4480

**Comment by xhochy** [comment]
We can use `inspect: update-grayskull` in conda-forge.yml instead. This is more reliable.

**Comment by connortann** [comment]
Sounds good. On which note I was a bit confused by the `bot` field in `conda-forge.yml`. There is a configuration which doesn't appear in the [docs](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#bot):

```yaml
bot:
  run_deps_from_wheel: true
````

Is that perhaps an outdated or incorrect item?

**Comment by xhochy** [comment]
This does something similar but the grayskull inspection is much more advanced.
