### ISSUE TITLE
Run pytest on build?

### ISSUE THREAD

**Issue by connortann** [conda-forge/shap-feedstock#59]
It might be helpful to run the pytest suite against the built package, to ensure the c extension is built correctly.

The shap tests use pytest's `importorskip` to skip any tests requiring optional 3rd party dependencies (such as tensorflow or pytorch). These tend to be the long-running tests.

So, perhaps a good place to start would be just running the "core" pytest tests. I'd be happy to take a stab as part of #57 if you agree with the suggestion.

**Comment by xhochy** [comment]
Sounds good!
