### ISSUE TITLE
Please add shap Python 3.12 conda-forge package

### ISSUE THREAD

**Issue by cdeil** [conda-forge/shap-feedstock#80]
### Comment:

@connortann - I saw in https://github.com/conda-forge/shap-feedstock/pull/79#issuecomment-1986896891 that you mentioned that shap should now support Python 3.12 and I do see at https://pypi.org/project/shap/#files that the Python 3.12 wheels are up.

However looking at https://anaconda.org/conda-forge/shap/files currently there's no Python 3.12 conda packages available.

Is it possible to add them, please?

**Comment by connortann** [comment]
I believe the release of shap on python 3.12 on conda-forge is currently contingent on all parent packages supporting python 3.12, and it looks like we are awaiting tensorflow. There is a dashbaord here that shows the status:

https://conda-forge.org/status/migration/python312

It looks like tensorflow will add support for 3.12 soon:

https://github.com/tensorflow/tensorflow/issues/62003

**Comment by cdeil** [comment]
@connortann - I thought tensorflow is just an optional or test dependency of shap, but e.g. shap with scikit-learn works just fine witout tensorflow?

So why wait for tensorflow 3.12 to make a shap conda package?

https://github.com/conda-forge/shap-feedstock/blob/f89b5c4499124ebf28f03d5c43ad4708e984db79/recipe/meta.yaml#L43-L54

https://github.com/shap/shap/blob/b1ec978518a1fae13f5146fe3078902e96a0f07e/pyproject.toml#L14-L24

**Comment by connortann** [comment]
Makes sense. It would be nice to get 3.12 support on conda-forge without waiting for tensorflow- do you know how this can be done?

All the information I can find points to the automatic migration above, which shows shap as a descendent of tensorflow. In our recipe.yaml, we only have tensorflow as a test dependency. I'm unsure if there is anything we can do, without removing the tensorflow tests (which seems rather drastic).

**Comment by cdeil** [comment]
@xhochy - can you help here? Why was SHAP not built for Python 3.12 yet when #79 was merged?
Is there still a blocking dependency or could it easily be done by changing some config setting?

**Comment by cdeil** [comment]
@xhochy - thank you!

shap works fine for me on Python 3.12 on MacOS. :-)
