### ISSUE TITLE
Numpy 2.0 Support

### ISSUE THREAD

**Issue by MCRE-BE** [conda-forge/shap-feedstock#86]
Hi

I noticed I am not able to update to Numpy 2.0.1. If I read the output from Mamba correctly, the dependency comes from Shap.

![image](https://github.com/user-attachments/assets/22460a88-8d96-4147-b45c-7c34988065d4)

I guess this is a not requested as I didn't see any limitation on numpy in the code. I therefore guess that it's a problem on the feedstock side. Can be seen on the CI side as well.

![image](https://github.com/user-attachments/assets/08917481-849d-41f9-ad99-c58e2c34d043)

I guess a simple rerender should solve this ?
I did notice that #85 does not solve thisand that's why I am opening a new issue.

**Comment by xhochy** [comment]
Numpy 2 support has landed meanwhile.
